main : com.clashwars.events.Events
name: Events
version: 0.1
description: ClashWars Events plugin.
depend: [CWCore]
commands:
  event:
    description: Main events command.
    usage: /<command>
    aliases: [events,ev,e]
  setup:
    description: Event/map setup commands.
    usage: /<command>
  leave:
    description: Player command to leave the current game.
    usage: /<command>
    aliases: [quit,hub,lobby]